import assert from "node:assert/strict";
import test from "node:test";

import { buildOpenHandoffs, buildRecentTeamMemory } from "./team-memory.js";
import type { ChunkExecution } from "../runtime/engine.js";

test("buildRecentTeamMemory summarizes recent chunk collaboration in Chinese", () => {
  const memory = buildRecentTeamMemory({
    locale: "zh-CN",
    chunkHistory: [
      {
        chunkNumber: 1,
        stageStartDay: 1,
        stageEndDay: 5,
        bossMessage: "先保守启动",
        rolePlans: [
          {
            role: "finance",
            roleLabel: "财务护栏",
            summary: "先控制预算。",
            watchouts: ["现金不能太快见底。"],
            handoffs: [
              {
                handoffId: "handoff-finance-1-1",
                fromRole: "finance",
                toRole: "marketing",
                note: "请在下一段控制投放预算。",
              },
            ],
            resolvedHandoffIds: [],
            actions: [],
          },
        ],
        actionSummary: "Kos 先压预算。",
        mergeRationale: "优先保护现金。",
        actions: [],
        executionSummary: "执行 agent 已按顺序落动作。",
        executionActionIds: [],
        executionResults: [],
        events: [],
        outcome: {
          orders: 8,
          revenue: 800,
          ad_spend: 150,
          total_cost_delta: 520,
          gross_profit_delta: 280,
          balance_end: 5280,
          inventory_end: 30,
          stock_pressure_level: "medium",
          summary_notes: [],
          best_channel: "tiktok",
          best_creative: "baseline",
          biggest_risk: "库存偏紧",
          biggest_win: "保住了现金",
        },
        artifact: {
          artifact_id: "a1",
          type: "chunk_update",
          created_at_day: 5,
          title: "Chunk 1 update",
          summary: "summary",
          day_start: 1,
          day_end: 5,
          orders: 8,
          revenue: 800,
          total_cost: 520,
          gross_profit: 280,
          balance: 5280,
          inventory_in_stock: 30,
          inventory_in_transit: 20,
          stock_pressure_level: "medium",
          biggest_win: "保住了现金",
          biggest_risk: "库存偏紧",
          best_channel: "tiktok",
          best_creative: "baseline",
          decision_point: "继续保守推进",
        },
      } satisfies ChunkExecution,
    ],
    openHandoffs: buildOpenHandoffs([
      {
        chunkNumber: 1,
        stageStartDay: 1,
        stageEndDay: 5,
        bossMessage: "先保守启动",
        rolePlans: [
          {
            role: "finance",
            roleLabel: "财务护栏",
            summary: "先控制预算。",
            watchouts: ["现金不能太快见底。"],
            handoffs: [
              {
                handoffId: "handoff-finance-1-1",
                fromRole: "finance",
                toRole: "marketing",
                note: "请在下一段控制投放预算。",
              },
            ],
            resolvedHandoffIds: [],
            actions: [],
          },
        ],
        actionSummary: "Kos 先压预算。",
        mergeRationale: "优先保护现金。",
        actions: [],
        executionSummary: "执行 agent 已按顺序落动作。",
        executionActionIds: [],
        executionResults: [],
        events: [],
        outcome: {
          orders: 8,
          revenue: 800,
          ad_spend: 150,
          total_cost_delta: 520,
          gross_profit_delta: 280,
          balance_end: 5280,
          inventory_end: 30,
          stock_pressure_level: "medium",
          summary_notes: [],
          best_channel: "tiktok",
          best_creative: "baseline",
          biggest_risk: "库存偏紧",
          biggest_win: "保住了现金",
        },
        artifact: {
          artifact_id: "a1",
          type: "chunk_update",
          created_at_day: 5,
          title: "Chunk 1 update",
          summary: "summary",
          day_start: 1,
          day_end: 5,
          orders: 8,
          revenue: 800,
          total_cost: 520,
          gross_profit: 280,
          balance: 5280,
          inventory_in_stock: 30,
          inventory_in_transit: 20,
          stock_pressure_level: "medium",
          biggest_win: "保住了现金",
          biggest_risk: "库存偏紧",
          best_channel: "tiktok",
          best_creative: "baseline",
          decision_point: "继续保守推进",
        },
      } satisfies ChunkExecution,
    ], 2),
  });

  assert.equal(memory.includes("第 1 段"), true);
  assert.equal(memory.includes("marketing:请在下一段控制投放预算"), true);
  assert.equal(memory.includes("优先保护现金"), true);
  assert.equal(memory.includes("当前交接待办"), true);
});

test("buildOpenHandoffs returns unresolved handoff tickets only", () => {
  const chunkHistory: ChunkExecution[] = [
    {
      chunkNumber: 1,
      stageStartDay: 1,
      stageEndDay: 5,
      bossMessage: "Start carefully",
      rolePlans: [
        {
          role: "finance",
          roleLabel: "Finance Guard",
          summary: "Protect cash.",
          watchouts: [],
          handoffs: [
            {
              handoffId: "handoff-finance-1-1",
              fromRole: "finance",
              toRole: "marketing",
              note: "Keep CAC discipline.",
            },
          ],
          resolvedHandoffIds: [],
          actions: [],
        },
      ],
      actionSummary: "Hold spend.",
      mergeRationale: "Cash first.",
      actions: [],
      executionSummary: "Executed nothing.",
      executionActionIds: [],
      executionResults: [],
      events: [],
      outcome: {
        orders: 0,
        revenue: 0,
        ad_spend: 0,
        total_cost_delta: 0,
        gross_profit_delta: 0,
        balance_end: 5000,
        inventory_end: 30,
        stock_pressure_level: "low",
        summary_notes: [],
      },
      artifact: {
        artifact_id: "a2",
        type: "chunk_update",
        created_at_day: 5,
        title: "Chunk 1 update",
        summary: "summary",
        day_start: 1,
        day_end: 5,
        orders: 0,
        revenue: 0,
        total_cost: 0,
        gross_profit: 0,
        balance: 5000,
        inventory_in_stock: 30,
        inventory_in_transit: 0,
        stock_pressure_level: "low",
        biggest_win: "No waste",
        biggest_risk: "Slow learning",
        best_channel: null,
        best_creative: null,
        decision_point: "Proceed carefully",
      },
    },
    {
      chunkNumber: 2,
      stageStartDay: 6,
      stageEndDay: 10,
      bossMessage: "Continue",
      rolePlans: [
        {
          role: "marketing",
          roleLabel: "Growth and Paid Media",
          summary: "Acknowledged CAC guardrail.",
          watchouts: [],
          handoffs: [],
          resolvedHandoffIds: ["handoff-finance-1-1"],
          actions: [],
        },
      ],
      actionSummary: "Still conservative.",
      mergeRationale: "Followed finance guardrail.",
      actions: [],
      executionSummary: "Executed nothing.",
      executionActionIds: [],
      executionResults: [],
      events: [],
      outcome: {
        orders: 0,
        revenue: 0,
        ad_spend: 0,
        total_cost_delta: 0,
        gross_profit_delta: 0,
        balance_end: 5000,
        inventory_end: 30,
        stock_pressure_level: "low",
        summary_notes: [],
      },
      artifact: {
        artifact_id: "a3",
        type: "chunk_update",
        created_at_day: 10,
        title: "Chunk 2 update",
        summary: "summary",
        day_start: 6,
        day_end: 10,
        orders: 0,
        revenue: 0,
        total_cost: 0,
        gross_profit: 0,
        balance: 5000,
        inventory_in_stock: 30,
        inventory_in_transit: 0,
        stock_pressure_level: "low",
        biggest_win: "No waste",
        biggest_risk: "Slow learning",
        best_channel: null,
        best_creative: null,
        decision_point: "Proceed carefully",
      },
    },
  ];

  const open = buildOpenHandoffs(chunkHistory);
  assert.equal(open.length, 0);
});

test("buildOpenHandoffs marks long-unresolved handoffs as stale", () => {
  const open = buildOpenHandoffs(
    [
      {
        chunkNumber: 1,
        stageStartDay: 1,
        stageEndDay: 5,
        bossMessage: "Start carefully",
        rolePlans: [
          {
            role: "finance",
            roleLabel: "Finance Guard",
            summary: "Protect cash.",
            watchouts: [],
            handoffs: [
              {
                handoffId: "handoff-finance-1-1",
                fromRole: "finance",
                toRole: "marketing",
                note: "Keep CAC discipline.",
              },
            ],
            resolvedHandoffIds: [],
            actions: [],
          },
        ],
        actionSummary: "Hold spend.",
        mergeRationale: "Cash first.",
        actions: [],
        executionSummary: "Executed nothing.",
        executionActionIds: [],
        executionResults: [],
        events: [],
        outcome: {
          orders: 0,
          revenue: 0,
          ad_spend: 0,
          total_cost_delta: 0,
          gross_profit_delta: 0,
          balance_end: 5000,
          inventory_end: 30,
          stock_pressure_level: "low",
          summary_notes: [],
        },
        artifact: {
          artifact_id: "a4",
          type: "chunk_update",
          created_at_day: 5,
          title: "Chunk 1 update",
          summary: "summary",
          day_start: 1,
          day_end: 5,
          orders: 0,
          revenue: 0,
          total_cost: 0,
          gross_profit: 0,
          balance: 5000,
          inventory_in_stock: 30,
          inventory_in_transit: 0,
          stock_pressure_level: "low",
          biggest_win: "No waste",
          biggest_risk: "Slow learning",
          best_channel: null,
          best_creative: null,
          decision_point: "Proceed carefully",
        },
      } satisfies ChunkExecution,
    ],
    4,
  );

  assert.equal(open.length, 1);
  assert.equal(open[0]?.ageInChunks, 3);
  assert.equal(open[0]?.isStale, true);
  assert.equal(open[0]?.priority, "stale");
});
